### ISSUE TITLE
`iterate(::ValueShapes.NamedTupleDist` not defined

### ISSUE THREAD

**Issue by Moelf** [oschulz/ValueShapes.jl#57]
should behave like a tuple in this regards?

**Comment by oschulz** [comment]
I didn't define iteration for it on purpose, since iteration over `Distributions.Product([Normal(), Normal()])`, which is also kind of a "collection" distributions, is not defined as well. I don't think Distributions.jl has clear guidelines here, though.

GIven `d = NamedTupleDist(...)`, I'm not sure if people would expect

```julia
logpdf.(d, X) == logpdf.(values(d), X)
```

or

```julia
logpdf.(d, X) == logpdf.(Ref(d), X)
```

so maybe it's safer to leave iteration undefined? `NamedTupleDist` does support `values(d)` and `(;d...)` though, to turn it into a `Tuple` resp. `NamedTuple` of distributions, it also supports `merge` with `NamedTupleDist`s and `NamedTuple`s of `Distributions.
